[tool.poetry]
name = "evalwrf"
version = "0.1.0"
description = ""
authors = ["Florian Ennemoser"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
xarray = "^2024.11.0"
matplotlib = "^3.9.2"
numpy = "^2.1.3"
cartopy = "^0.24.1"
pandas = "^2.2.3"
cdsapi = "^0.7.4"
pytest = "^8.3.3"
geopandas = "^1.0.1"
jupyterlab = "^4.3.1"
httpx = "0.27.0"
tqdm = "^4.67.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
