[CUSTOM_BOUNDARYS]
styria = "D:\\WRF\\downloads\\Steiermark_Bezirksgrenzen"

[WINDTURBINE]
ATTRIBUTE_COLS = ["Nabenh√∂he (m)","Durchmesser (m)","Standing Thrust Coeffcient","Nennleistung (MW)"]
DATA_COLS = ["wind_speed_ms-1","thrust_coeff","power_produktion_kW"]
LOCATION_COLS = ["Latitude","Longitude","Index Value"]
